name: get shakemaps
on:
  workflow_dispatch:
  schedule:
    - cron: '3/5 * * * *'

env: 
  AWS_ID: ${{ secrets.AWS_ID }}
  AWS_SECRET: ${{ secrets.AWS_SECRET }}
  BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
  BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

jobs:
  get_shakemaps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: npm install
      - run: npm install playwright-chromium
      - run: yarn get-data
      - run: yarn wait
      - run: yarn screenshot-and-tweet
      - run: yarn update-timestamp
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          add_options: last-updated.txt

